const sb=supabase.createClient(OFFHOURS_CONFIG.supabaseUrl,OFFHOURS_CONFIG.supabaseKey),q=new URLSearchParams(location.search),gn=+q.get("group");let eid,gid,route=[],pid,pname="",cur=0,sips=1,saved={};const $=s=>document.querySelector(s);
if(!Number.isInteger(gn)||gn<1||gn>5){$("#error").textContent="Ungültiger Gruppenlink. Bitte QR-Code eurer Gruppe scannen.";$("#joinForm button").disabled=true}else $("#groupBadge").textContent=`GROUP 0${gn}`;
async function init(){if(!gn)return;let{data:e,error:a}=await sb.from("events").select("id").eq("name",OFFHOURS_CONFIG.eventName).single();if(a)return err("Event konnte nicht geladen werden.");eid=e.id;let{data:g,error:b}=await sb.from("groups").select("id").eq("event_id",eid).eq("group_number",gn).single();if(b)return err("Gruppe konnte nicht geladen werden.");gid=g.id;let{data:r,error:c}=await sb.from("route_stops").select("id,position,hole:holes(bar_name,drink,par)").eq("group_id",gid).order("position");if(c)return err("Route konnte nicht geladen werden.");route=r;let l=JSON.parse(localStorage.getItem(`oh_g${gn}`)||"null");if(l?.pid){({pid,pname,saved={},cur=0}=l);show()}}init();
function err(t){$("#error").textContent=t}function persist(){localStorage.setItem(`oh_g${gn}`,JSON.stringify({pid,pname,saved,cur}))}
$("#joinForm").onsubmit=async e=>{e.preventDefault();pname=$("#name").value.trim();if(!pname)return;pid=crypto.randomUUID();let{error}=await sb.from("players").insert({id:pid,event_id:eid,group_id:gid,name:pname});if(error)return err("Anmeldung fehlgeschlagen: "+error.message);persist();show()};
function show(){$("#join").classList.add("hidden");$("#finish").classList.add("hidden");$("#score").classList.remove("hidden");$("#player").textContent=pname;render()}
function render(){let s=route[cur],h=s.hole;$("#num").textContent=String(cur+1).padStart(2,"0");$("#par").textContent=`PAR ${h.par}`;$("#barName").textContent=h.bar_name;$("#drink").textContent=h.drink;$("#progressText").textContent=`${cur+1} / 9`;$("#bar").style.width=`${(cur+1)/9*100}%`;sips=saved[s.id]??1;$("#value").textContent=sips;$("#prev").style.visibility=cur?"visible":"hidden";$("#next").style.visibility=cur<8?"visible":"hidden";$("#msg").textContent=saved[s.id]!=null?"✓ GESPEICHERT":""}
$("#minus").onclick=()=>{$("#value").textContent=sips=Math.max(1,sips-1)};$("#plus").onclick=()=>{$("#value").textContent=sips=Math.min(99,sips+1)};$("#prev").onclick=()=>{if(cur){cur--;persist();render()}};$("#next").onclick=()=>{if(cur<8){cur++;persist();render()}};
$("#save").onclick=async()=>{let s=route[cur],{error}=await sb.from("scores").upsert({player_id:pid,route_stop_id:s.id,sips,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"player_id,route_stop_id"});if(error)return $("#msg").textContent="Fehler: "+error.message;saved[s.id]=sips;if(cur===8){persist();await finish()}else{cur++;persist();render()}};
async function finish(){await sb.from("players").update({completed:true}).eq("id",pid);$("#score").classList.add("hidden");$("#finish").classList.remove("hidden");$("#finishName").textContent=pname.toUpperCase();$("#total").textContent=Object.values(saved).reduce((a,b)=>a+ +b,0)}$("#review").onclick=()=>{cur=0;persist();show()};